name: Validate CITATION.cff

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'CITATION.cff'
      - '.github/workflows/cff-validator.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Validate-CITATION-cff:
    runs-on: ubuntu-latest
    name: Validate CITATION.cff
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Validate CITATION.cff
        uses: dieghernan/cff-validator@v5
