name: Validate CITATION.cff

on:
  push:
    branches: ["main"]
    paths:
      - 'CITATION.cff'
      - '.github/workflows/cff-validator.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'CITATION.cff'
      - '.github/workflows/cff-validator.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Validate-CITATION-cff:
    runs-on: ubuntu-24.04
    name: Validate CITATION.cff
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-citation
      cancel-in-progress: true
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Validate CITATION.cff
        uses: dieghernan/cff-validator@v5
