# This action compiles the library and driver and runs all unit tests using an OS and CMake matrix
name: Unit Tests

on:
  push:
    branches: ["main"]
    paths:
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - '.gitmodules'
      - '.github/workflows/ctest.yml'
      - 'app/**'
      - 'extern/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - '.gitmodules'
      - '.github/workflows/ctest.yml'
      - 'app/**'
      - 'extern/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:

permissions:
  contents: read

# Define the matrix for different operating systems
jobs:
  build-and-test:
    name: ${{ matrix.os }} / ${{ matrix.architecture }} / CMake ${{ matrix.cmakeVersion }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.cmakeVersion }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15            # Apple
          - macos-15-intel      # Intel
          - windows-2025
        architecture: [arm64, x64, x86]
        cmakeVersion: ["3.21.0", "4.4.2"] # Test the minimum supported version and the current stable release.
        exclude:
          - os: macos-15
            architecture: x86
          - os: macos-15
            architecture: x64
          - os: macos-15-intel
            architecture: x86
          - os: macos-15-intel
            architecture: arm64
          - os: windows-2025
            architecture: arm64
          - os: ubuntu-24.04
            architecture: arm64
          - os: ubuntu-24.04
            architecture: x86
          - os: windows-2025
            cmakeVersion: "3.21.0"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Clone required submodules # TODO-TEMPLATE: Add test-data submodule here, if needed
      run: |
        git submodule init extern/googletest
        git submodule update

    - name: Install CMake
      uses: lukka/get-cmake@v4.4.2
      with:
        cmakeVersion: ${{ matrix.cmakeVersion }}

    - name: "CMake: Build and Test (64-bit)"
      if: matrix.architecture != 'x86'
      uses: lukka/run-cmake@v10
      with:
        configurePreset: release64
        configurePresetAdditionalArgs: "['-DBUILD_DOCS=OFF']"
        buildPreset: release64
        testPreset: release64

    - name: "CMake: Build and Test (32-bit)"
      if: matrix.architecture == 'x86'
      uses: lukka/run-cmake@v10
      with:
        configurePreset: release32
        configurePresetAdditionalArgs: "['-DBUILD_DOCS=OFF']"
        buildPreset: release32
        testPreset: release32
